### ISSUE TITLE
Buttons, primary and secondary

### ISSUE THREAD

**Issue by soniaturcotte** [citizensadvice/design-system#10]
<img width="250" alt="Group 2 (2)" src="https://user-images.githubusercontent.com/52572549/74851444-26f13180-5333-11ea-9403-7ab7bbf97994.png">

## Notes for further iteration

Disabled buttons. We generally recommend not using them, unless research strongly suggests that there is a user need. 

Consider links styled as buttons and buttons styled as links. 
This should be tested in context of specific forms when it comes up. 

Buttons on dark background (this is currently being used by Scams) White button style?

**Decision that previous will be a secondary button:**
- In keeping with our current styles 
- Rhona has seen research that shows buttons are easier for people with cognitive difficulties
- link looked quite unnoticeable in context of the page 
- Want to prevent people from clicking the back button as this will mean they lose all their progress so it should be obvious

**Comment by soniaturcotte** [comment]
Design work in progress: https://www.figma.com/file/IZY9uqY9RPjhIUv8ol1qjf/Design-System-Experimentation?node-id=232%3A0

**Comment by shakiradamji** [comment]
Tried a gradient from green to Teal to try and find an accessible colour that is close to #81cec6 but meets contrast requirements against white.

**Comment by soniaturcotte** [comment]
Some other things we need to consider: 

Buttons on dark background (this is currently being used by Scams) White button style? 

Next and previous buttons as a pattern, do both need to be buttons or could "previous" be link text? Kostas will explore this in the scams tool iteration

**Comment by shakiradamji** [comment]
Look at design options for secondary button active state
