### ISSUE TITLE
Run engine tests against multiple Rails versions

### ISSUE THREAD

**Issue by davidsauntson** [citizensadvice/design-system#1394]
Related to DS-37: Run engine tests against multiple Ruby versionsTO DO . Different product teams run different versions of Rails.

We should run the engine tests in a matrix against different versions:

- Rails 6.0
- Rails 6.1 
- Edge Rails? (main branch)

This is a little more fiddly that ruby versions but we can use a similar approach to this: https://github.com/primer/view_components/blob/main/Gemfile#L6-L26

**Comment by davidrapson** [comment]
Closed in https://github.com/citizensadvice/design-system/pull/1833
