### ISSUE TITLE
Error Summary View Component

### ISSUE THREAD

**Issue by davidsauntson** [citizensadvice/design-system#1417]
# Error Summary View Component

Use the existing styles for error summary to create a view component that can be used with forms to surface error messages and provide links to the erroring fields.

- does your component need to be used by other products or services?
> Yes - it will be needed for any product that has a user facing form with validation

- does something similar already exist in the design system
> The styles for this component exist already, and this proposed component uses them.

- is there a product team that would perform the research, design, development and QA work associate with building this component?
> Probably content-platform?

- do you have any user stories / scenarios that describe the component?
> As a user, I want to see a list of problems with my form submission, so that I can correct my mistakes and submit the form correctly

> As a user, I want to be able to get from an error message to the part of the form with the wrong information in quickly so I can rectify my mistake and submit the form correctly

### Code

- provide a link to your component working in a dev or prod environment
>component class, template, spec and preview are in this public-website PR: https://github.com/citizensadvice/public-website/pull/1689

### Usability

 - have you tested the component with the intended user group? Please include any links to research documentation in your proposal
> TBC but the styles exist already so assume this is covered.  Worth trying to find the research for tho to attach to documentation.

### Accessibility
- have you ensured your component meets WCAG 2.X AA guidelines? Include test protocols from external audits or notes from internal tests
> Styles and react implementation have been audited by the Digital Accessibility Centre as part of the second public-website audit (see report here https://citizensadvice.atlassian.net/wiki/spaces/NP/pages/2526347313/Accessibility+reviews+-+external).  It might be worth explicitly testing a journey with an invalid form submission as something to test in the next audit

- have you tested your component with a screen reader?
> Yes, using Chrome and VoiceOver on a Mac.  I wonder if hearing 'Enter your name' when that link has focus is confusing and if we should make it explicit that clicking the link will take you to the invalid form field?

- have you tested your component by using only the keyboard to interact with it?
> Yes, works.

### Quality

- provide links to any appropriate automated tests you have written
  - unit tests
> `rspec` unit tests in PR link above

  - behavioural tests
  - visual regression tests
 > these might be easier to do when part of the design system?

### Rough migration dev outline:
- [x] create new component in `design-system/engine` project
- [x] move ruby code and HAML into files created above - it no longer needs to be scoped to `PublicAdvice`
- [x] move rspec for component into `design-system/engine` project
- [x] update storybook docs so that:
  - [x] they use the HTML generated by the `rake generate_examples` task in `/demo`
  - [x] they provide instructions on how to use the view component and detail the interface (see other components for example)
- [x] create a visual regression test for the error summary component (if there isn't one already)
- do an alpha release
- do a full release

**Comment by marianayovcheva** [comment]
Link to an example: **https://web.develop.content.citizensadvice.org.uk/components/previews/citizens_advice_components/error_summary/example/**
