### ISSUE TITLE
Components

### ISSUE THREAD

**Issue by anneliwesterberg** [citizensadvice/design-system#1556]
Documentation template and guidance on how to document:

- General
- Design
- Developer
- Content
- Research
- Accessibility

https://docs.google.com/document/d/1qbrWXa-UFaG29iHff4enqqB4xYd2okqoAxe9xDWFESw/edit#

**Comment by JamesR-CA** [comment]
Draft component template with a live example for 'Targeted Content'.
Worked on with Daniel N and Alex E.
