### ISSUE TITLE
Build process & deployment

### ISSUE THREAD

**Issue by davidsauntson** [citizensadvice/design-system#1647]
Use [Netlify](https://www.netlify.com/) for hosting and deployment.  Let's start with the free tier and see what it's like.  We should be able to:
- get Netlify to create a hosted version of the docs site when a PR is created
- have a link to that preview site added to the PR in github automatically
- have the updated version of the site deployed when we merge into`main`

Notes from tech discussion:

**How will we host / deploy it?**

- Spike into using Netlify for deployment and hosting
- Gain benefits of PR / branch previews - helps devs and content editors
- Not worth effort of setting up custom AWS deployments etc
- Minimal cost - will need some budget if spike proves solution is good

**Comment by davidrapson** [comment]
We've done this now, see an example here: https://62629cce51ba33184c90d49d--ca-design-system.netlify.app/
