### ISSUE TITLE
Sidebar component

### ISSUE THREAD

**Issue by davidsauntson** [citizensadvice/design-system#1670]
# Sidebar

Public website, AdviserNet, Intranet and the new design-system docs site all use the same sidebar styles despite them not being part of the design system.

The time has come to extract a generic component for the sidebar that allows us to:
- provide a sidebar title ('Related content')
- provide a section title ('Applying to the EU settlement scheme')
- provide an optional section title url (sometimes they are links, sometimes they aren't)
- a list of links

<img src="https://user-images.githubusercontent.com/2331893/144083882-659159ef-6f6e-4e3b-957f-979b3e6a0698.png" width="300" />

Figma - https://www.figma.com/file/Im9r6ZM1YWiJK488OWx8a6/AdviserNet-Template-Redesign?node-id=785%3A107

- does your component need to be used by other products or services?
> public website, intranet, design-system docs, advisernet

- does something similar already exist in the design system
> no

- is there a product team that would perform the research, design, development and QA work associate with building this component?

> content-platform has already done this (it is live, eg on https://www.citizensadvice.org.uk/immigration/staying-in-the-uk-if-youre-from-the-eu/)

- do you have any user stories / scenarios that describe the component?
> not currently

### Code

- provide a link to your component working in a dev or prod environment
> https://www.citizensadvice.org.uk/immigration/staying-in-the-uk-if-youre-from-the-eu/

- provide links to the code for this component
> https://github.com/citizensadvice/public-website/blob/develop/app/components/related_content_component.rb
> https://github.com/citizensadvice/public-website/blob/develop/app/components/related_content_component.html.haml

### Usability

- have you tested the component with the intended user group? Please include any links to research documentation in your proposal
> yes, tbc with Kostas

### Accessibility

- have you ensured your component meets WCAG 2.X AA guidelines? Include test protocols from external audits or notes from internal tests
- have you tested your component with a screen reader?
- have you tested your component by using only the keyboard to interact with it?

> yes, it has been covered by the journeys in the DAC audit for public-website

### Quality

- provide links to any appropriate automated tests you have written
  - unit tests https://github.com/citizensadvice/public-website/blob/develop/spec/components/related_content_component_spec.rb
  - behavioural tests n/a
  - visual regression tests https://github.com/citizensadvice/public-website/blob/1e244262a297943a1acb04f710edbd8f6dddfa35/testing/visual-regression/scenarios/public-advice.js#L39

**Comment by davidsauntson** [comment]
The public advice pages also display a list of 'Adviser' only links when a user is logged in.  I suggest that this is not considered part of this component and that if a consuming product wants to amend the component in that way, it can create a bespoke version of the component that wraps the design-system component and extends it as required (eg as we do with headers) https://github.com/citizensadvice/public-website/blob/1e244262a297943a1acb04f710edbd8f6dddfa35/app/components/public_advice/header_component.rb#L16

**Comment by anneliwesterberg** [comment]
Agree that it seems sensible to make the component general and not having a set of links for a logged in state. I think there is space for misinterpretation of how to use this component anyway (we've seen external agencies using it as in-page navigation), so better keep it as simple as possible and let the teams who need something slightly different tweak it themselves.

**Comment by davidrapson** [comment]
Couple of thoughts from how we've used this in Intranet land:

- For advice content I believe this component currently removes the current page from the list. For intranet content we show all pages including the current one so would be great to keep that filtering logic at the product level if we make a Rails component version
- We've been discussing removing, or at least renaming, the "Related content" prefix as that's a very generic—if harmless—label so again useful if the Rails version of the component let you swap that out.

But otherwise makes sense to start thinking about sharing this.

> we've seen external agencies using it as in-page navigation

This is interesting @anneliwesterberg any examples of where this is being used like this?

**Comment by anneliwesterberg** [comment]
@davidrapson It was in a prototype a consultancy created for client self-serve debt assessment earlier this year, so not implemented anywhere. Kostas spotted it when we reviewed it. It was before that team had a designer, so they used some budget they had to have a consultancy build them a prototype.
