### ISSUE TITLE
Error summary links scrolling past the form legend

### ISSUE THREAD

**Issue by marianayovcheva** [citizensadvice/design-system#1694]
## Summary of problem
Error summary links scroll past the form legend, to see the legend, the users need to scroll up

## Steps to replicate
1. Scroll to the bottom of a [content page](https://www.citizensadvice.org.uk/immigration/staying-in-the-uk-if-youre-from-the-eu/) and from the advice feedback section ('Did this advice help?') select **No**
2. This will open a form - submit the form without filling in the form (we want to see the error message appear)
3. When the error summary appears, click on a link (in the example case 'Select an option')

## Expected behaviour
When clicking on a link from the error summary, this should scroll the user to the legend before the input so that the user is aware what needs to be adjusted in their input

## Actual behavior
When clicking on a link from the error summary, the page scrolls to the input, past the legend which means that the user would need to scroll up to check what they need to input
## Context

- url - content pages, example: https://www.citizensadvice.org.uk/immigration/staying-in-the-uk-if-youre-from-the-eu/
- screenshot
  - actual
![image](https://user-images.githubusercontent.com/94383569/145395625-bf0bea52-9d6f-499b-a0b8-8e5beaeda6c5.png)
  - expected
![image](https://user-images.githubusercontent.com/94383569/145395702-d6d9d251-01f6-4525-a486-cf1597a09c99.png)

- browser / os / device - any

**Comment by marianayovcheva** [comment]
This actually exists in Jira: https://citizensadvice.atlassian.net/jira/software/c/projects/NP/boards/208?modal=detail&selectedIssue=NP-2423&search=error%20summary

**Comment by davidrapson** [comment]
This has been fixed
