### ISSUE TITLE
Global Navigation

### ISSUE THREAD

**Issue by shakiradamji** [citizensadvice/design-system#17]
### Description
 Global navigation used across all pages on the public site. 

**user need**
Provides users with an easy and consistent way to navigate to the main sections of the website

Navigation is greedy so links that show depend on the screen size, [see an example of a greedy nav](https://codepen.io/lukejacksonn/pen/PwmwWV)

### Small screens, 0 - 768px
**Small screen menu closed**
![global-nav-mobile-closed](https://user-images.githubusercontent.com/52572549/73559162-73400480-444c-11ea-8c7c-df9cd6d87301.png)

**Small screen menu open**

- Menu slides down from the top
- When it's open the more button changes to close 
- Tapping the close button hides the menu (slide up) 
- 'Debt & money' shows menu focus state 
- 'Family' shows menu hover state
- Links from the header (sign in etc) move to the bottom of the menu

![Group 83](https://user-images.githubusercontent.com/52572549/73753355-7859c800-475a-11ea-9da6-fa9392b33745.png)

### Large screens, 768px and above
**Menu closed**
![global-nav-large-screen](https://user-images.githubusercontent.com/52572549/73559656-64a61d00-444d-11ea-8072-2ad9200cea1f.png)

**Menu open**
![Group 84](https://user-images.githubusercontent.com/52572549/73753327-6d069c80-475a-11ea-9a2d-3aded932005d.png)

**Global nav link hover**
![global-nav-link-hover](https://user-images.githubusercontent.com/52572549/73559804-af279980-444d-11ea-9756-42e63b293ff8.png)

**Global nav link focus**
![global-nav-link-focus](https://user-images.githubusercontent.com/52572549/73559796-ac2ca900-444d-11ea-9711-46762dcf5f98.png)

**Global nav link Hover menu**
- Only show on the large screen breakpoint
- Only show for global nav link items that are visible in the main navigation bar (not in the 'more' menu) 
- Show on Hover 
- Size of the hover menus does not change depending on screen size 
- Top links show as a separate column
- If there are no top links the menu is one column
- Top links are manually set in the CMS 
- If there are only top links the menu is one column 
- A view all link is always visible at the bottom of the menu, this takes the user to the landing page. 

![global-nav-largescreen-menu](https://user-images.githubusercontent.com/52572549/73559885-d8e0c080-444d-11ea-96c1-d32a7b34b721.png)

**Comment by panosvoudouris** [comment]
@shakiradamji Where do we get the little up/down arrow icon for the Cloes button?

**Comment by shakiradamji** [comment]
> up/down arrow icon for the Cloes button?

We need to work on icons. You can use the fontawesome SVG for now https://fontawesome.com/icons/chevron-down?style=solid. @soniaturcotte mentioned making the arrow using CSS?
