### ISSUE TITLE
Internal links treated as external when using the design system locally

### ISSUE THREAD

**Issue by marianayovcheva** [citizensadvice/design-system#1761]
## Summary of problem
When using the design system on local sites (e.g on public-website), internal links get external links style. This happens because the link doesn't start with `https://www.citizensadvice.org.uk` as specified here: https://github.com/citizensadvice/design-system/blob/main/scss/1-settings/_prose.scss. 

This happens on pages that use .cads-prose (e.g: http://localhost:3000/immigration/bringing-family-to-live-in-the-uk-after-brexit/).

## Expected behaviour
First link is internal and has no external icon
![image](https://user-images.githubusercontent.com/94383569/152568575-aa7c0d46-9d36-49cb-b801-e485daad7ec8.png)

## Actual behaviour
First link is internal but gets external icon
![image](https://user-images.githubusercontent.com/94383569/152570714-96d3052a-ffc0-4548-8722-ff0d118566ca.png)

## Proposed solution
Most of the internal urls actually begin with `/` and not `http` a possible solution to the problem could be:
```
  a:not([href^="https://www.citizensadvice.org.uk"]):not([href^="/"]):not([href^="#"])::after
  {
    @media not print {
      @include cads-hyperlink--external-icon();
    }
  }
```
- `[href^="https://www.citizensadvice.org.uk"]` - in case there are urls that are internal but begin with the full url
- `[href^="/"]` - most of the internal links 
- `[href^="#"]` - possible hashes

**Comment by davidsauntson** [comment]
This bug presumably also causes internal links on non-prod domains to be rendered with an external link icon too (if they aren't relative links).

Another option would be to change the current `$cads-internal-link-domain` SASS variable to a [list](https://sass-lang.com/documentation/values/lists), and create a rule based on each value in the map.  This would allow users of the design system to have more control
