### ISSUE TITLE
Select component

### ISSUE THREAD

**Issue by marianayovcheva** [citizensadvice/design-system#1784]
# Select
Adding a new select component as part of our Form components. 
The component should be used in limited scenarios as there are usability concerns. 

[Design (dropdown)
](https://www.figma.com/file/J9qfbS9n1pUM2dpRQnTXUD/Design-system?node-id=1361%3A20&viewport=690%2C12%2C0.6274107098579407)

## Accessibility 
Suggesting keeping the options list using the native styles and default browser interactivity for best accessibility (see 'Basic keyboard behavior' section of [this article](https://www.24a11y.com/2019/select-your-poison/))

## Usability
[External user research](https://www.youtube.com/watch?v=CUkMCQR4TpY) has shown that users struggle with the select component and it should be only used where no other component can be used (e.g if it cannot be replaced with radio buttons or text input). We should clearly indicate this in the design system docs and discourage unnecessary use of the component.

The design system working group is here to support you through the contribution process - to help them, please consider the following:

- does your component need to be used by other products or services?
> not currently but can be used in the future (e.g there is a potential use case in casebook)
- does something similar already exist in the design system
> no
- is there a product team that would perform the research, design, development and QA work associate with building this component?
> not currently
- do you have any user stories / scenarios that describe the component?
> not currently

**Comment by davidsauntson** [comment]
Helloooo - I've implemented a select using the existing view components here: https://github.com/citizensadvice/energy-comparison-table/pull/82

We needed it for the customer service ratings table - LMK if I should contribute this back into the design system 😊

**Comment by marianayovcheva** [comment]
@davidsauntson I think it would be great if we have a select component in the design system. Do you know if the design team is happy for the styles to be reused in the design system? I can also bring it up in the design system monthly meeting if that helps

**Comment by marianayovcheva** [comment]
https://github.com/citizensadvice/design-system/pull/3019
