### ISSUE TITLE
Grids

### ISSUE THREAD

**Issue by soniaturcotte** [citizensadvice/design-system#2]
### Breakpoints
Small screen breakpoint: 320px
Large screen breakpoint: 768px
Extra large breakpoint: 1024px (however we won't be designing for this before migration)

Min width: N/A
Max width: 1024px (footer and header backgrounds extend to the edge of the page)

### Grids
Small screens (0px to 768px)
Columns: 1
Margin: 16px
Gutter: N/A

Max text width 592px, when it reaches this width footer and header colours stretch to 767px but the text and any callout boxes are contained and aligned to the left of the screen.

Large screens (768px and above)
Columns: 4
Margin: 32px
Gutter: 32px

Max text width on advice collections 592px. Research was done by Adam Parsons, Lyndsey Johnson and Chris Brett into this. Optimum line length for reading. Need to consider what happens to the space between the text and section navigation - this will look odd if it's too wide.

Navigation is greedy so stacks depending on screen size, not when it gets to the breakpoint.

### Design considerations
User data on devices from the past 6 months:
320 ~4% of users
360 ~12% of users
375px ~19% of users
414px ~10% of users

Larger screen sizes more commonly used, consider optimizing designs for 375px
Navigation and footer on 320px and 767px - the smallest and largest it's likely to be

[View the designs](Designs: https://www.figma.com/file/IZY9uqY9RPjhIUv8ol1qjf/Design-System-Experimentation?node-id=0%3A1)

**Comment by shakiradamji** [comment]
### Breakpoints 

Small screen breakpoint: 320px
Large screen breakpoint: 768px 
Extra large breakpoint: 1024px (however we won't be designing for this before migration)

Min width: 320px 
Max width: 1024px (footer and header backgrounds extend to the edge of the page)

User data on devices from the past 6 months:
320 ~4% of users
360 ~12% of users
375px ~19% of users 
414px ~10% of users 

Most common screen sizes are 375px so consider optimizing the design for this screen size. 

### Grids

**Small screens (320px)** 
Columns: 1
Margin: 16px
Gutter: N/A


**Large screens (768px)**
Columns: 4
Margin: 32px 
Gutter: 32px

**Comment by shakiradamji** [comment]
Designs: https://www.figma.com/file/IZY9uqY9RPjhIUv8ol1qjf/Design-System-Experimentation?node-id=0%3A1

**Comment by soniaturcotte** [comment]
@shakiradamji @panosvoudouris this is done right ?

**Comment by shakiradamji** [comment]
> @shakiradamji @panosvoudouris this is done right ?

Yes as far as I know it's done
