### ISSUE TITLE
Form inputs and text areas

### ISSUE THREAD

**Issue by soniaturcotte** [citizensadvice/design-system#25]
<img width="305" alt="Group 110 (2)" src="https://user-images.githubusercontent.com/52572549/74853996-99174580-5336-11ea-9939-4a0a3066faa1.png">

### Form input sizes
![Group 111 (1)](https://user-images.githubusercontent.com/52572549/74852146-1c836780-5334-11ea-9946-355b23923d57.png)

**Comment by shakiradamji** [comment]
Experiment with using the error indication in the margin so nothing moves 
Experiment with input error styles on the same page as important callouts

**Comment by shakiradamji** [comment]
What happens to radios and checkboxes with text that flows onto multiple lines?

**Comment by shakiradamji** [comment]
Should we use optional or required for forms?
- Look over our forms - do we usually have more stuff that's optional or more stuff that's required?
- Do some user testing
- Agree on a standard that will be used consistently across the whole site
