### ISSUE TITLE
Radios and checkboxes

### ISSUE THREAD

**Issue by soniaturcotte** [citizensadvice/design-system#26]
<img width="219" alt="Group 107" src="https://user-images.githubusercontent.com/52572549/74850873-61a69a00-5332-11ea-8751-49f82e7713d3.png">
<img width="164" alt="Did this advice help_" src="https://user-images.githubusercontent.com/52572549/74850888-666b4e00-5332-11ea-8cd4-477ae1643a80.png">

**Comment by shakiradamji** [comment]
Update documentation about why we’ve changed from grey box

Add designs for smaller version and guidance on when and why to use them
