### ISSUE TITLE
Replace `ActiveSupport::Deprecation.warn` due to deprecation

### ISSUE THREAD

**Issue by pksterling** [citizensadvice/design-system#3073]
## Summary of problem
`ActiveSupport::Deprecation.warn` is used in a few parts of the codebase. This is to be deprecated.

## Steps to replicate
Use a deprecated feature, e.g. use the `title` attribute in the `callout` component

## Expected behaviour
No deprecation warning

## Actual behavior
The following warning `DEPRECATION WARNING: Calling warn on ActiveSupport::Deprecation is deprecated and will be removed from Rails (use your own Deprecation object instead)`

**Comment by davidrapson** [comment]
Fixed by https://github.com/citizensadvice/design-system/pull/3074
